app:
    build: .
    volumes:
      - ./src:/home/app/code/src
    command: node index.js
    ports:
      - "8000"
    links:
      - redis:redis_data
    environment:
      - NODE_ENV=production
      - API_SECRET=1

redis:
    image: tutum/redis:latest
    environment:
      - REDIS_PASS=**None**
